<?php
  //POBLAR CORRECTAMENETE EL ARREGLO 
  $_POST = json_decode(file_get_contents("php://input"),true);
  // EXTRAEMOS LAS INPUTS, NO LOS INPUTS, SINO LA INPUT QUE EL USUARIO NOS MANDA POR DATA EN EL AJAX


  echo json_encode($_POST); //SI ESTAMOS USANDO URENCODE SE MANDA DIRECTO,
  //SINO DEBEMOS DE HACER EL DECODE QUE ESTA RRIBA
?>
